server:
  port: 8084

spring:
  application:
    name: gateway

  data:
    redis:
      host: localhost
      port: 6379


  cloud:
    gateway:
      routes:
        - id: company_service
          uri: lb://COMPANY-SERVICE
          predicates:
            - Path=/external/companies/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                key-resolver: "#{@ipKeyResolver}"


        - id: job_service
          uri: lb://JOB-SERVICE-DEV
          predicates:
            - Path=/jobs/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                key-resolver: "#{@ipKeyResolver}"

        - id: review_service
          uri: lb://REVIEW-SERVICE
          predicates:
            - Path=/external/reviews/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                key-resolver: "#{@ipKeyResolver}"

        - id: eureka-server
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/main
          filters:
            - SetPath=/

        - id: eureka-server-static
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**

        - id: user_service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/external/users/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                key-resolver: "#{@ipKeyResolver}"


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: false

management:
  tracing:
    sampling:
      probability: 1.0

logging:
  level:
    root: info
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: INFO

